version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "/usr/local/bin/php /var/www/worker.php"

otel:
  insecure: true
  compress: false
  client: http
  exporter: otlp
  service_name: rr # your app name
  service_version: 1.0.0 # your app version
  endpoint: otel-collector:4318


http:
  address: "0.0.0.0:8080"
  middleware: [gzip, otel] # otel middleware should be applied first in the line (from right to left). Middleware order is: `request` --> `otel` -> `gzip` -> `http-plugin` -> `PHP worker`.

logs:
  level: info
  output: stdout